---
# tasks file for COMPOSER
- name: Download Composer installer
  become: true
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php

- name: Run the Composer installer
  become: true
  shell: "php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer"